/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.edu.ijse.assignment.ui;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Hansani Kariyawasam
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
        pnlSideNav.setBackground(new Color(133, 141, 144));
        setLocationRelativeTo(null);
        pnlDash.setBackground(new Color(210, 240, 252 ));
        loadPanel(new PlaceNewOrder());
    }
    private void loadPanel(JPanel panel){
        pnlDash.removeAll();
        pnlDash.revalidate();
        pnlDash.add(panel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDash = new javax.swing.JPanel();
        lblAddItem = new javax.swing.JLabel();
        lblManageOrder = new javax.swing.JLabel();
        lblPlaceOrder = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlSideNav = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDash.setLayout(new java.awt.CardLayout());
        getContentPane().add(pnlDash, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 670, 519));

        lblAddItem.setBackground(new java.awt.Color(133, 141, 144));
        lblAddItem.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAddItem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAddItem.setText("      Add Item");
        lblAddItem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblAddItem.setOpaque(true);
        lblAddItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAddItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAddItemMouseExited(evt);
            }
        });
        getContentPane().add(lblAddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 190, 70));

        lblManageOrder.setBackground(new java.awt.Color(133, 141, 144));
        lblManageOrder.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblManageOrder.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblManageOrder.setText("      Manage Order");
        lblManageOrder.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblManageOrder.setOpaque(true);
        lblManageOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageOrderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblManageOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblManageOrderMouseExited(evt);
            }
        });
        getContentPane().add(lblManageOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 190, 70));

        lblPlaceOrder.setBackground(new java.awt.Color(133, 141, 144));
        lblPlaceOrder.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblPlaceOrder.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPlaceOrder.setText("      Place New Order");
        lblPlaceOrder.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblPlaceOrder.setOpaque(true);
        lblPlaceOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPlaceOrderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPlaceOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPlaceOrderMouseExited(evt);
            }
        });
        getContentPane().add(lblPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 190, 70));

        jLabel1.setFont(new java.awt.Font("Tiranti Solid LET", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thogakade");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 190, 50));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/assignment/images/icons8-US Dollar-80.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 130, 90));

        pnlSideNav.setOpaque(true);
        getContentPane().add(pnlSideNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 519));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblManageOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageOrderMouseEntered
        lblManageOrder.setBackground(new Color(161, 169, 172  ));
    }//GEN-LAST:event_lblManageOrderMouseEntered

    private void lblAddItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddItemMouseEntered
        lblAddItem.setBackground(new Color(161, 169, 172  ));
    }//GEN-LAST:event_lblAddItemMouseEntered

    private void lblAddItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddItemMouseExited
        lblAddItem.setBackground(new Color(133, 141, 144));
    }//GEN-LAST:event_lblAddItemMouseExited

    private void lblPlaceOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlaceOrderMouseEntered
        lblPlaceOrder.setBackground(new Color(161, 169, 172  ));
    }//GEN-LAST:event_lblPlaceOrderMouseEntered

    private void lblPlaceOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlaceOrderMouseExited
        lblPlaceOrder.setBackground(new Color(133, 141, 144));
    }//GEN-LAST:event_lblPlaceOrderMouseExited

    private void lblManageOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageOrderMouseExited
        lblManageOrder.setBackground(new Color(133, 141, 144));
    }//GEN-LAST:event_lblManageOrderMouseExited

    private void lblAddItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddItemMouseClicked
        loadPanel(new AddItem());
        AddItem.txtDescription.requestFocus();
    }//GEN-LAST:event_lblAddItemMouseClicked

    private void lblPlaceOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlaceOrderMouseClicked
        loadPanel(new PlaceNewOrder());
    }//GEN-LAST:event_lblPlaceOrderMouseClicked

    private void lblManageOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageOrderMouseClicked
        loadPanel(new ManageOrder());
    }//GEN-LAST:event_lblManageOrderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAddItem;
    private javax.swing.JLabel lblManageOrder;
    private javax.swing.JLabel lblPlaceOrder;
    private javax.swing.JPanel pnlDash;
    private javax.swing.JLabel pnlSideNav;
    // End of variables declaration//GEN-END:variables
}
